"""sua mensagem de migração

Revision ID: 885d519d1186
Revises: 
Create Date: 2024-10-02 17:51:18.333926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885d519d1186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    # ### end Alembic commands ###
