"""Asset

Revision ID: cb5d72cfb735
Revises: 885d519d1186
Create Date: 2024-10-07 10:36:53.606808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5d72cfb735'
down_revision = '885d519d1186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filial', sa.String(length=50), nullable=True),
    sa.Column('cod_base_bem', sa.String(length=100), nullable=True),
    sa.Column('codigo_item', sa.String(length=50), nullable=True),
    sa.Column('tipo_ativo', sa.String(length=50), nullable=True),
    sa.Column('historico', sa.String(length=200), nullable=True),
    sa.Column('conta', sa.String(length=50), nullable=True),
    sa.Column('tipo_deprec', sa.String(length=50), nullable=True),
    sa.Column('ativo_origem', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('produto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('preco', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('asset')
    # ### end Alembic commands ###
